# vs-split-traffic.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productcatalogservice
  namespace: frontend
spec:
  hosts:
    - productcatalogservice.product-catalog.svc.cluster.local
  http:
    - match:
        - port: 3550
      route:
        - destination:
            host: productcatalogservice.product-catalog.svc.cluster.local
            subset: v1
            port:
              number: 3550
          weight: 80
        - destination:
            host: productcatalogservice.product-catalog.svc.cluster.local
            subset: v2
            port:
              number: 3550
          weight: 20
